NAME_MIN_LENGTH = 2
NAME_MAX_LENGTH = 50

EMAIL_MIN_LENGTH = 5
EMAIL_MAX_LENGTH = 100

PHONE_MIN_LENGTH = 8
PHONE_MAX_LENGTH = 20

ADDITIONAL_INFO_MAX_LENGTH = 255

USER_NAME_MIN_LENGTH = 2
USER_NAME_MAX_LENGTH = 50

USER_PASSWORD_MIN_LENGTH = 6
USER_PASSWORD_MAX_LENGTH = 12

ROLE_USER = "USER"
ROLE_MODERATOR = "MODERATOR"
ROLE_ADMIN = "ADMIN"
